Added RKE module
terraform-rancher-modules/terraform-infra-aws pull request #2
Opened 2023-02-15 05:48 UTC by suryatejaboorlu

2023-02-15 18:24 UTC, leodotcloud requested changes

2023-02-15 18:24 UTC, leodotcloud commented on aws/ami.tf
> +    values = ["ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"]
Do we need this? Aren't things working on 22.04?

2023-02-15 18:24 UTC, leodotcloud commented on aws/keys.tf
> +  key_name   = "surya-test-keypair"
Plz remove this hardcoding, use a variable.

2023-02-15 18:24 UTC, leodotcloud commented on aws/nodes.tf
> +  cluster_id_tag = {
Please add comments on what's this for?

2023-02-15 18:24 UTC, leodotcloud commented on aws/nodes.tf
> +  count = 4
Hard coding here as well.

2023-02-15 18:24 UTC, leodotcloud commented on aws/nodes.tf
> +resource "aws_instance" "rke-node" {
`rke-node`: Plz ensure the naming conventions are similar to other folders.

2023-02-15 18:24 UTC, leodotcloud commented on aws/nodes.tf
> +  iam_instance_profile   = "rk-all-role"
Do we really need an IAM instance profile?

2023-02-15 18:24 UTC, leodotcloud commented on aws/nodes.tf
> +      user        = "ubuntu"
Hard coding.

2023-02-15 18:24 UTC, leodotcloud commented on aws/nodes.tf
> +      "curl ${var.docker_install_url} | sh",
Plz ensure this is how we are installing docker in the other module as well.

2023-02-15 18:24 UTC, leodotcloud commented on aws/nodes.tf
> +      "sudo usermod -a -G docker ubuntu",
Hardcoding.

2023-02-15 18:24 UTC, leodotcloud commented on aws/output.tf
> +output "addresses" {
Same for the outputs too. Plz follow the same convention as other module.

2023-03-02 03:43 UTC, closed without merging

2023-03-02 03:44 UTC, suryatejaboorlu commented
Closing as this code is not up to our requirement.